spring:
  datasource:
    name: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.1.115:3306/cyy5?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    application:
       name: serviceconsumer

  dubbo:
    application:
      name: house_provider
    registry:
      address: zookeeper://127.0.0.1:2181
    scan: com.jk.service


mybatis:
  mapperLocations: classpath*:mybatis/*Mapper.xml

  redis:
     host=192.168.149.1
     port=6379
     pass=
     maxIdle=300
     maxActive=600
     maxWait=1000
     testOnBorrow=true


server:
  port: 8082
